// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: testdata/types.proto

package testdata

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	group "github.com/cosmos/modules/incubator/group"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MyAppMsg is the payload stored with a proposal and executed when approved
type MyAppMsg struct {
	// Types that are valid to be assigned to Sum:
	//	*MyAppMsg_A
	//	*MyAppMsg_B
	//	*MyAppMsg_C
	//	*MyAppMsg_D
	//	*MyAppMsg_E
	Sum isMyAppMsg_Sum `protobuf_oneof:"sum"`
}

func (m *MyAppMsg) Reset()         { *m = MyAppMsg{} }
func (m *MyAppMsg) String() string { return proto.CompactTextString(m) }
func (*MyAppMsg) ProtoMessage()    {}
func (*MyAppMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2447ab8d7bf628b8, []int{0}
}
func (m *MyAppMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MyAppMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MyAppMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MyAppMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyAppMsg.Merge(m, src)
}
func (m *MyAppMsg) XXX_Size() int {
	return m.Size()
}
func (m *MyAppMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_MyAppMsg.DiscardUnknown(m)
}

var xxx_messageInfo_MyAppMsg proto.InternalMessageInfo

type isMyAppMsg_Sum interface {
	isMyAppMsg_Sum()
	MarshalTo([]byte) (int, error)
	Size() int
}

type MyAppMsg_A struct {
	A *MsgAlwaysSucceed `protobuf:"bytes,1,opt,name=A,proto3,oneof" json:"A,omitempty"`
}
type MyAppMsg_B struct {
	B *MsgAlwaysFail `protobuf:"bytes,2,opt,name=B,proto3,oneof" json:"B,omitempty"`
}
type MyAppMsg_C struct {
	C *MsgSetValue `protobuf:"bytes,3,opt,name=C,proto3,oneof" json:"C,omitempty"`
}
type MyAppMsg_D struct {
	D *MsgIncCounter `protobuf:"bytes,4,opt,name=D,proto3,oneof" json:"D,omitempty"`
}
type MyAppMsg_E struct {
	E *MsgConditional `protobuf:"bytes,5,opt,name=E,proto3,oneof" json:"E,omitempty"`
}

func (*MyAppMsg_A) isMyAppMsg_Sum() {}
func (*MyAppMsg_B) isMyAppMsg_Sum() {}
func (*MyAppMsg_C) isMyAppMsg_Sum() {}
func (*MyAppMsg_D) isMyAppMsg_Sum() {}
func (*MyAppMsg_E) isMyAppMsg_Sum() {}

func (m *MyAppMsg) GetSum() isMyAppMsg_Sum {
	if m != nil {
		return m.Sum
	}
	return nil
}

func (m *MyAppMsg) GetA() *MsgAlwaysSucceed {
	if x, ok := m.GetSum().(*MyAppMsg_A); ok {
		return x.A
	}
	return nil
}

func (m *MyAppMsg) GetB() *MsgAlwaysFail {
	if x, ok := m.GetSum().(*MyAppMsg_B); ok {
		return x.B
	}
	return nil
}

func (m *MyAppMsg) GetC() *MsgSetValue {
	if x, ok := m.GetSum().(*MyAppMsg_C); ok {
		return x.C
	}
	return nil
}

func (m *MyAppMsg) GetD() *MsgIncCounter {
	if x, ok := m.GetSum().(*MyAppMsg_D); ok {
		return x.D
	}
	return nil
}

func (m *MyAppMsg) GetE() *MsgConditional {
	if x, ok := m.GetSum().(*MyAppMsg_E); ok {
		return x.E
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MyAppMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MyAppMsg_A)(nil),
		(*MyAppMsg_B)(nil),
		(*MyAppMsg_C)(nil),
		(*MyAppMsg_D)(nil),
		(*MyAppMsg_E)(nil),
	}
}

type MyAppProposal struct {
	Base group.ProposalBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base"`
	Msgs []MyAppMsg         `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs"`
}

func (m *MyAppProposal) Reset()         { *m = MyAppProposal{} }
func (m *MyAppProposal) String() string { return proto.CompactTextString(m) }
func (*MyAppProposal) ProtoMessage()    {}
func (*MyAppProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_2447ab8d7bf628b8, []int{1}
}
func (m *MyAppProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MyAppProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MyAppProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MyAppProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyAppProposal.Merge(m, src)
}
func (m *MyAppProposal) XXX_Size() int {
	return m.Size()
}
func (m *MyAppProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MyAppProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MyAppProposal proto.InternalMessageInfo

// MsgAlwaysSucceed is handled without errors
type MsgAlwaysSucceed struct {
}

func (m *MsgAlwaysSucceed) Reset()         { *m = MsgAlwaysSucceed{} }
func (m *MsgAlwaysSucceed) String() string { return proto.CompactTextString(m) }
func (*MsgAlwaysSucceed) ProtoMessage()    {}
func (*MsgAlwaysSucceed) Descriptor() ([]byte, []int) {
	return fileDescriptor_2447ab8d7bf628b8, []int{2}
}
func (m *MsgAlwaysSucceed) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAlwaysSucceed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAlwaysSucceed.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAlwaysSucceed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAlwaysSucceed.Merge(m, src)
}
func (m *MsgAlwaysSucceed) XXX_Size() int {
	return m.Size()
}
func (m *MsgAlwaysSucceed) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAlwaysSucceed.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAlwaysSucceed proto.InternalMessageInfo

// MsgAlwaysFail returns an error by the handler
type MsgAlwaysFail struct {
}

func (m *MsgAlwaysFail) Reset()         { *m = MsgAlwaysFail{} }
func (m *MsgAlwaysFail) String() string { return proto.CompactTextString(m) }
func (*MsgAlwaysFail) ProtoMessage()    {}
func (*MsgAlwaysFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_2447ab8d7bf628b8, []int{3}
}
func (m *MsgAlwaysFail) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAlwaysFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAlwaysFail.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAlwaysFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAlwaysFail.Merge(m, src)
}
func (m *MsgAlwaysFail) XXX_Size() int {
	return m.Size()
}
func (m *MsgAlwaysFail) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAlwaysFail.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAlwaysFail proto.InternalMessageInfo

// MsgSetValue stores a value in the store
type MsgSetValue struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *MsgSetValue) Reset()         { *m = MsgSetValue{} }
func (m *MsgSetValue) String() string { return proto.CompactTextString(m) }
func (*MsgSetValue) ProtoMessage()    {}
func (*MsgSetValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_2447ab8d7bf628b8, []int{4}
}
func (m *MsgSetValue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetValue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetValue.Merge(m, src)
}
func (m *MsgSetValue) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetValue.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetValue proto.InternalMessageInfo

func (m *MsgSetValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// MsgIncCounter increments a counter value
type MsgIncCounter struct {
}

func (m *MsgIncCounter) Reset()         { *m = MsgIncCounter{} }
func (m *MsgIncCounter) String() string { return proto.CompactTextString(m) }
func (*MsgIncCounter) ProtoMessage()    {}
func (*MsgIncCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_2447ab8d7bf628b8, []int{5}
}
func (m *MsgIncCounter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIncCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIncCounter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIncCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIncCounter.Merge(m, src)
}
func (m *MsgIncCounter) XXX_Size() int {
	return m.Size()
}
func (m *MsgIncCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIncCounter.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIncCounter proto.InternalMessageInfo

// MsgConditional execution depends on persistent counter value. When not equal then execution fails.
type MsgConditional struct {
	ExpectedCounter uint64 `protobuf:"varint,1,opt,name=expectedCounter,proto3" json:"expectedCounter,omitempty"`
}

func (m *MsgConditional) Reset()         { *m = MsgConditional{} }
func (m *MsgConditional) String() string { return proto.CompactTextString(m) }
func (*MsgConditional) ProtoMessage()    {}
func (*MsgConditional) Descriptor() ([]byte, []int) {
	return fileDescriptor_2447ab8d7bf628b8, []int{6}
}
func (m *MsgConditional) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConditional) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConditional.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConditional) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConditional.Merge(m, src)
}
func (m *MsgConditional) XXX_Size() int {
	return m.Size()
}
func (m *MsgConditional) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConditional.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConditional proto.InternalMessageInfo

func (m *MsgConditional) GetExpectedCounter() uint64 {
	if m != nil {
		return m.ExpectedCounter
	}
	return 0
}

type MsgPropose struct {
	Base group.MsgProposeBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base"`
	Msgs []MyAppMsg           `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs"`
}

func (m *MsgPropose) Reset()         { *m = MsgPropose{} }
func (m *MsgPropose) String() string { return proto.CompactTextString(m) }
func (*MsgPropose) ProtoMessage()    {}
func (*MsgPropose) Descriptor() ([]byte, []int) {
	return fileDescriptor_2447ab8d7bf628b8, []int{7}
}
func (m *MsgPropose) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPropose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPropose.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPropose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPropose.Merge(m, src)
}
func (m *MsgPropose) XXX_Size() int {
	return m.Size()
}
func (m *MsgPropose) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPropose.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPropose proto.InternalMessageInfo

func (m *MsgPropose) GetBase() group.MsgProposeBase {
	if m != nil {
		return m.Base
	}
	return group.MsgProposeBase{}
}

func (m *MsgPropose) GetMsgs() []MyAppMsg {
	if m != nil {
		return m.Msgs
	}
	return nil
}

func init() {
	proto.RegisterType((*MyAppMsg)(nil), "cosmos_modules.incubator.group.v1_alpha.testdata.MyAppMsg")
	proto.RegisterType((*MyAppProposal)(nil), "cosmos_modules.incubator.group.v1_alpha.testdata.MyAppProposal")
	proto.RegisterType((*MsgAlwaysSucceed)(nil), "cosmos_modules.incubator.group.v1_alpha.testdata.MsgAlwaysSucceed")
	proto.RegisterType((*MsgAlwaysFail)(nil), "cosmos_modules.incubator.group.v1_alpha.testdata.MsgAlwaysFail")
	proto.RegisterType((*MsgSetValue)(nil), "cosmos_modules.incubator.group.v1_alpha.testdata.MsgSetValue")
	proto.RegisterType((*MsgIncCounter)(nil), "cosmos_modules.incubator.group.v1_alpha.testdata.MsgIncCounter")
	proto.RegisterType((*MsgConditional)(nil), "cosmos_modules.incubator.group.v1_alpha.testdata.MsgConditional")
	proto.RegisterType((*MsgPropose)(nil), "cosmos_modules.incubator.group.v1_alpha.testdata.MsgPropose")
}

func init() { proto.RegisterFile("testdata/types.proto", fileDescriptor_2447ab8d7bf628b8) }

var fileDescriptor_2447ab8d7bf628b8 = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xc1, 0x6a, 0xd4, 0x40,
	0x18, 0xc7, 0x33, 0xdd, 0xac, 0xe8, 0xb7, 0xd4, 0xea, 0xb0, 0x87, 0xd0, 0x43, 0x5a, 0xe2, 0xc1,
	0xc5, 0xd2, 0x44, 0x57, 0x44, 0x58, 0x10, 0xdd, 0x6c, 0x2b, 0x0a, 0x86, 0xd6, 0x54, 0x3c, 0x78,
	0x59, 0x66, 0x93, 0x21, 0x1b, 0x4c, 0x32, 0x21, 0x33, 0xa9, 0xee, 0x1b, 0x78, 0xf4, 0x11, 0x7c,
	0x08, 0xbd, 0xf9, 0x00, 0xc5, 0x53, 0x2f, 0x82, 0x27, 0x91, 0xdd, 0x17, 0x91, 0x4c, 0x66, 0xed,
	0x6e, 0xbd, 0xd4, 0x2d, 0x78, 0xcb, 0x7c, 0x64, 0x7e, 0xdf, 0xff, 0xfb, 0xff, 0x3f, 0x06, 0xda,
	0x82, 0x72, 0x11, 0x12, 0x41, 0x1c, 0x31, 0xc9, 0x29, 0xb7, 0xf3, 0x82, 0x09, 0x86, 0xef, 0x06,
	0x8c, 0xa7, 0x8c, 0x0f, 0x53, 0x16, 0x96, 0x09, 0xe5, 0x76, 0x9c, 0x05, 0xe5, 0x88, 0x08, 0x56,
	0xd8, 0x51, 0xc1, 0xca, 0xdc, 0x3e, 0xbe, 0x37, 0x24, 0x49, 0x3e, 0x26, 0xf6, 0xfc, 0xf6, 0xe6,
	0x8e, 0x18, 0xc7, 0x45, 0x38, 0xcc, 0x49, 0x21, 0x26, 0x8e, 0x84, 0x38, 0x35, 0x63, 0x77, 0xf1,
	0x50, 0xe3, 0x37, 0xdb, 0x11, 0x8b, 0x58, 0x5d, 0xaf, 0xbe, 0x54, 0xf5, 0xa6, 0x64, 0x2f, 0xea,
	0xb0, 0xbe, 0x37, 0xe0, 0xaa, 0x37, 0xe9, 0xe7, 0xb9, 0xc7, 0x23, 0xec, 0x03, 0xea, 0x1b, 0x68,
	0x1b, 0x75, 0x5a, 0x5d, 0xd7, 0xfe, 0x57, 0x81, 0xb6, 0xc7, 0xa3, 0x7e, 0xf2, 0x8e, 0x4c, 0xf8,
	0x51, 0x19, 0x04, 0x94, 0x86, 0xcf, 0x34, 0x1f, 0xf5, 0xf1, 0x01, 0x20, 0xd7, 0x58, 0x93, 0xcc,
	0xc7, 0x97, 0x60, 0x3e, 0x25, 0x71, 0x52, 0x01, 0x5d, 0xec, 0x01, 0x1a, 0x18, 0x0d, 0x09, 0x7c,
	0xb4, 0x12, 0xf0, 0x88, 0x8a, 0xd7, 0x24, 0x29, 0x69, 0x85, 0x1b, 0x54, 0xfa, 0xf6, 0x0c, 0xfd,
	0x12, 0xfa, 0x9e, 0x67, 0xc1, 0x80, 0x95, 0x99, 0xa0, 0x45, 0x05, 0xdc, 0xc3, 0x87, 0x80, 0xf6,
	0x8d, 0xa6, 0x04, 0x3e, 0x59, 0x09, 0x38, 0x60, 0x59, 0x18, 0x8b, 0x98, 0x65, 0x44, 0x4e, 0xbc,
	0xdf, 0xdb, 0xf9, 0xf6, 0x79, 0xf7, 0xf6, 0x9d, 0x28, 0x16, 0xe3, 0x72, 0x64, 0x07, 0x2c, 0x55,
	0x51, 0xcf, 0xe3, 0xe7, 0xe1, 0x5b, 0x15, 0xa9, 0xc7, 0x23, 0xb7, 0x09, 0x0d, 0x5e, 0xa6, 0xd6,
	0x57, 0x04, 0xeb, 0x32, 0xd7, 0xc3, 0x82, 0xe5, 0x8c, 0x93, 0x04, 0x1f, 0x80, 0x3e, 0x22, 0x9c,
	0xaa, 0x7c, 0x1f, 0x5c, 0x58, 0xda, 0x1c, 0xe0, 0x12, 0x4e, 0x5d, 0xfd, 0xe4, 0xe7, 0x96, 0xe6,
	0x4b, 0x10, 0x7e, 0x05, 0x7a, 0xca, 0x23, 0x6e, 0xac, 0x6d, 0x37, 0x3a, 0xad, 0x6e, 0x6f, 0x85,
	0x59, 0xd5, 0xde, 0xcd, 0xa9, 0x15, 0xad, 0xa7, 0x7f, 0xf8, 0xb4, 0xa5, 0x59, 0x18, 0x6e, 0x9c,
	0x5f, 0x27, 0x6b, 0x03, 0xd6, 0x97, 0xd6, 0xc1, 0xba, 0x05, 0xad, 0x85, 0x38, 0x71, 0x1b, 0x9a,
	0xc7, 0xd5, 0x87, 0x9c, 0xf0, 0x9a, 0x5f, 0x1f, 0xd4, 0xad, 0xb3, 0x90, 0xac, 0x1e, 0x5c, 0x5f,
	0x36, 0x19, 0x77, 0x60, 0x83, 0xbe, 0xcf, 0x69, 0x20, 0x68, 0xa8, 0x7e, 0x92, 0x08, 0xdd, 0x3f,
	0x5f, 0xb6, 0xbe, 0x20, 0x00, 0x8f, 0x47, 0xb5, 0x25, 0x14, 0xbf, 0x5c, 0xb2, 0xf4, 0xe1, 0x85,
	0x1d, 0x38, 0x43, 0xfc, 0x1f, 0x53, 0xdd, 0x17, 0x27, 0x53, 0x13, 0x9d, 0x4e, 0x4d, 0xf4, 0x6b,
	0x6a, 0xa2, 0x8f, 0x33, 0x53, 0x3b, 0x9d, 0x99, 0xda, 0x8f, 0x99, 0xa9, 0xbd, 0xe9, 0xfe, 0xbd,
	0x56, 0xaa, 0x97, 0xf3, 0xa7, 0x97, 0xa3, 0x9e, 0x0d, 0xd5, 0x62, 0x74, 0x45, 0x3e, 0x1d, 0xf7,
	0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x5d, 0x62, 0xa4, 0xda, 0x04, 0x00, 0x00,
}

func (this *MyAppMsg) GetMsg() github_com_cosmos_cosmos_sdk_types.Msg {
	if x := this.GetA(); x != nil {
		return x
	}
	if x := this.GetB(); x != nil {
		return x
	}
	if x := this.GetC(); x != nil {
		return x
	}
	if x := this.GetD(); x != nil {
		return x
	}
	if x := this.GetE(); x != nil {
		return x
	}
	return nil
}

func (this *MyAppMsg) SetMsg(value github_com_cosmos_cosmos_sdk_types.Msg) error {
	if value == nil {
		this.Sum = nil
		return nil
	}
	switch vt := value.(type) {
	case *MsgAlwaysSucceed:
		this.Sum = &MyAppMsg_A{vt}
		return nil
	case *MsgAlwaysFail:
		this.Sum = &MyAppMsg_B{vt}
		return nil
	case *MsgSetValue:
		this.Sum = &MyAppMsg_C{vt}
		return nil
	case *MsgIncCounter:
		this.Sum = &MyAppMsg_D{vt}
		return nil
	case *MsgConditional:
		this.Sum = &MyAppMsg_E{vt}
		return nil
	}
	return fmt.Errorf("can't encode value of type %T as message MyAppMsg", value)
}

func (m *MyAppMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MyAppMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MyAppMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sum != nil {
		{
			size := m.Sum.Size()
			i -= size
			if _, err := m.Sum.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *MyAppMsg_A) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MyAppMsg_A) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.A != nil {
		{
			size, err := m.A.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *MyAppMsg_B) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MyAppMsg_B) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.B != nil {
		{
			size, err := m.B.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *MyAppMsg_C) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MyAppMsg_C) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.C != nil {
		{
			size, err := m.C.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *MyAppMsg_D) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MyAppMsg_D) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.D != nil {
		{
			size, err := m.D.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *MyAppMsg_E) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MyAppMsg_E) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.E != nil {
		{
			size, err := m.E.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *MyAppProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MyAppProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MyAppProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Msgs) > 0 {
		for iNdEx := len(m.Msgs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Msgs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Base.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgAlwaysSucceed) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAlwaysSucceed) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAlwaysSucceed) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAlwaysFail) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAlwaysFail) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAlwaysFail) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgIncCounter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIncCounter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIncCounter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgConditional) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConditional) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConditional) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpectedCounter != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExpectedCounter))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgPropose) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPropose) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPropose) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Msgs) > 0 {
		for iNdEx := len(m.Msgs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Msgs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Base.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MyAppMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Sum != nil {
		n += m.Sum.Size()
	}
	return n
}

func (m *MyAppMsg_A) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.A != nil {
		l = m.A.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *MyAppMsg_B) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.B != nil {
		l = m.B.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *MyAppMsg_C) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.C != nil {
		l = m.C.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *MyAppMsg_D) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.D != nil {
		l = m.D.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *MyAppMsg_E) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.E != nil {
		l = m.E.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}
func (m *MyAppProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Base.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.Msgs) > 0 {
		for _, e := range m.Msgs {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *MsgAlwaysSucceed) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAlwaysFail) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *MsgIncCounter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgConditional) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ExpectedCounter != 0 {
		n += 1 + sovTypes(uint64(m.ExpectedCounter))
	}
	return n
}

func (m *MsgPropose) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Base.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.Msgs) > 0 {
		for _, e := range m.Msgs {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MyAppMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MyAppMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MyAppMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field A", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &MsgAlwaysSucceed{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &MyAppMsg_A{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field B", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &MsgAlwaysFail{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &MyAppMsg_B{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field C", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &MsgSetValue{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &MyAppMsg_C{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field D", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &MsgIncCounter{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &MyAppMsg_D{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field E", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &MsgConditional{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Sum = &MyAppMsg_E{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MyAppProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MyAppProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MyAppProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Base", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Base.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msgs = append(m.Msgs, MyAppMsg{})
			if err := m.Msgs[len(m.Msgs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAlwaysSucceed) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAlwaysSucceed: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAlwaysSucceed: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAlwaysFail) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAlwaysFail: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAlwaysFail: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIncCounter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIncCounter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIncCounter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConditional) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConditional: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConditional: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpectedCounter", wireType)
			}
			m.ExpectedCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpectedCounter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPropose) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPropose: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPropose: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Base", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Base.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msgs = append(m.Msgs, MyAppMsg{})
			if err := m.Msgs[len(m.Msgs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
